package manifoldsampleproject.extensions.abc.res.movies;

import abc.res.movies; // note 'movies' is a class
import manifold.ext.rt.api.Extension;
import manifold.ext.rt.api.This;
import manifold.science.measures.Length;
import manifold.science.measures.LengthUnit;

/**
 * Demonstrates extension methods on an inner class generated by a type manifold, in this case the using the GraphQL
 * Manifold for the {@code movies} type.
 */
@Extension
public class MyMoviesExt {
    public static class Person {
        public static class Builder {
            /**
             * Add a {@code withHeight()} on inner class {@link movies.Person.Builder} utilizing {@link LengthUnit}
             */
            public static movies.Person.Builder withHeight(@This movies.Person.Builder thiz, Length height) {
                return thiz.withHeight(height.to(LengthUnit.Meter).toNumber().doubleValue());
            }
        }
    }
}
